        <table style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; text-align: left; width: 98%; margin: 20px auto;">
          <tr style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
            <td style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 5px 0;" valign="top">
              <p style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 5px 0;">Sayın <strong>{#firma_adi#}</strong>,<br> <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 İş Başvuru Formunuz Başarıyla İletilmiştir.  <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" /><br>
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Adınız : </strong> {#adiniz#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Soyadınız : </strong> {#soyadiniz#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Doğum Yeriniz : </strong> {#dogumyeriniz#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Doğum Tarihiniz : </strong> {#dogumtarihiniz#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Cinsiyetiniz : </strong> {#cinsiyetiniz#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Uyruğunuz : </strong> {#uyrugunuz#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>İkametgah Adresiniz : </strong> {#ikametgahadresiniz#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Ev Telefonunuz : </strong> {#evtelefonunuz#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Cep Telefonunuz : </strong> {#ceptelefonunuz#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Eposta Adresiniz : </strong> {#epostaadresiniz#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Askerlik Durumunuz : </strong> {#askerlikdurumunuz#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>B Sürücü Belgesi : </strong> {#b_belgesi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>C Sürücü Belgesi : </strong> {#c_belgesi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>D Sürücü Belgesi : </strong> {#d_belgesi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>E Sürücü Belgesi : </strong> {#e_belgesi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>F Sürücü Belgesi : </strong> {#f_belgesi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Sürücü Belgesi Yok : </strong> {#belgeyok#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Medeni Durumunuz : </strong> {#medenidurumunuz#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Sigara Kullanıyor musunuz? : </strong> {#sigarakullaniyormunusuz#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>İlköğretim Okul Adı : </strong> {#ilkogretim_okuladi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>İlköğretim Bölümü : </strong> {#ilkogretim_bolumu#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>İlköğretim Başlangıç Tarihi : </strong> {#ilkogretim_baslangictarihi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>İlköğretim Bitiş Tarihi : </strong> {#ilkogretim_bitistarihi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>lköğretim Mezuniyet Derecesi : </strong> {#ilkogretim_mezuniyetderecesi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Lise Okul Adı : </strong> {#lise_okuladi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Lise Bölümü : </strong> {#lise_bolumu#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Lise Başlangıç Tarihi : </strong> {#ilkogretim_baslangictarihi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Lise Bitiş Tarihi : </strong> {#lise_bitistarihi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Lise Mezuniyet Derecesi : </strong> {#lise_mezuniyetderecesi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>ÖnLisans Okul Adı : </strong> {#onlisans_okuladi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>ÖnLisans Bölümü : </strong> {#onlisans_bolumu#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>ÖnLisans Başlangıç Tarihi : </strong> {#onlisans_baslangictarihi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>ÖnLisans Bitiş Tarihi : </strong> {#onlisans_bitistarihi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>ÖnLisans Mezuniyet Derecesi : </strong> {#onlisans_mezuniyetderecesi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Lisans Okul Adı : </strong> {#lisans_okuladi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Lisans Bölümü : </strong> {#lisans_bolumu#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Lisans Başlangıç Tarihi : </strong> {#lisans_baslangictarihi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Lisans Bitiş Tarihi : </strong> {#lisans_bitistarihi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Lisans Mezuniyet Derecesi : </strong> {#lisans_mezuniyetderecesi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Yüksek Lisans Okul Adı : </strong> {#ylisans_okuladi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Yüksek Lisans Bölümü : </strong> {#ylisans_bolumu#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Yüksek Lisans Başlangıç Tarihi : </strong> {#ylisans_baslangictarihi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Yüksek Lisans Bitiş Tarihi : </strong> {#ylisans_bitistarihi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Yüksek Lisans Mezuniyet Derecesi : </strong> {#ylisans_mezuniyetderecesi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Doktora Okul Adı : </strong> {#doktora_okuladi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Doktora Bölümü : </strong> {#doktora_bolumu#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Doktora Başlangıç Tarihi : </strong> {#doktora_baslangictarihi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Doktora Bitiş Tarihi : </strong> {#doktora_bitistarihi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Doktora Mezuniyet Derecesi : </strong> {#doktora_mezuniyetderecesi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Dil 1 : </strong> {#dil1#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Dil 1 Okuma : </strong> {#dil1_okuma#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Dil 1 Yazma : </strong> {#dil1_yazma#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Dil 1 Konuşma : </strong> {#dil1_konusma#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Dil 2 : </strong> {#dil2#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Dil 2 Okuma : </strong> {#dil2_okuma#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Dil 2 Yazma : </strong> {#dil2_yazma#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Dil 2 Konuşma : </strong> {#dil2_konusma#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Dil 3 : </strong> {#dil3#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Dil 3 Okuma : </strong> {#dil3_okuma#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Dil 3 Yazma : </strong> {#dil3_yazma#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Dil 3 Konuşma : </strong> {#dil3_konusma#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Bigisayar Bilgisi Excel : </strong> {#bilgisayar_excel#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Bigisayar Bilgisi Word : </strong> {#bilgisayar_word#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Bigisayar Bilgisi Powerpoint : </strong> {#bilgisayar_powerpoint#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Bigisayar Bilgisi Diğer : </strong> {#bilgisayar_diger#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>İş Tecrübesi 1 Firma Kurum/Adı : </strong> {#is1_firmakurum#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>İş Tecrübesi 1 Göreviniz : </strong> {#is1_gorev#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>İş Tecrübesi 1 Giriş Tarihi : </strong> {#is1_giris#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>İş Tecrübesi 1 Çıkış Tarihi : </strong> {#is1_cikis#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>İş Tecrübesi 1 Ayrılma Sebebiniz : </strong> {#is1_ayrilmasebep#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>İş Tecrübesi 2 Firma Kurum/Adı : </strong> {#is2_firmakurum#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>İş Tecrübesi 2 Göreviniz : </strong> {#is2_gorev#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>İş Tecrübesi 2 Giriş Tarihi : </strong> {#is2_giris#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>İş Tecrübesi 2 Çıkış Tarihi : </strong> {#is2_cikis#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>İş Tecrübesi 2 Ayrılma Sebebiniz : </strong> {#is2_ayrilmasebep#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>İş Tecrübesi 3 Firma Kurum/Adı : </strong> {#is3_firmakurum#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>İş Tecrübesi 3 Göreviniz : </strong> {#is3_gorev#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>İş Tecrübesi 3 Giriş Tarihi : </strong> {#is3_giris#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>İş Tecrübesi 3 Çıkış Tarihi : </strong> {#is3_cikis#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>İş Tecrübesi 3 Ayrılma Sebebiniz : </strong> {#is3_ayrilmasebep#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>İş Tecrübesi 4 Firma Kurum/Adı : </strong> {#is4_firmakurum#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>İş Tecrübesi 4 Göreviniz : </strong> {#is4_gorev#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>İş Tecrübesi 4 Giriş Tarihi : </strong> {#is4_giris#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>İş Tecrübesi 4 Çıkış Tarihi : </strong> {#is4_cikis#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>İş Tecrübesi 4 Ayrılma Sebebiniz : </strong> {#is4_ayrilmasebep#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Kurs/Seminer/Sertifika/Ödül ve Takditler 1 Konu : </strong> {#kursseminer1_konu#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Kurs/Seminer/Sertifika/Ödül ve Takditler 1 Kurum : </strong> {#kursseminer1_kurum#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Kurs/Seminer/Sertifika/Ödül ve Takditler 1 Süre : </strong> {#kursseminer1_sure#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Kurs/Seminer/Sertifika/Ödül ve Takditler 1 Tarih : </strong> {#kursseminer1_tarih#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Kurs/Seminer/Sertifika/Ödül ve Takditler 2 Konu : </strong> {#kursseminer2_konu#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Kurs/Seminer/Sertifika/Ödül ve Takditler 2 Kurum : </strong> {#kursseminer2_kurum#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Kurs/Seminer/Sertifika/Ödül ve Takditler 2 Süre : </strong> {#kursseminer2_sure#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Kurs/Seminer/Sertifika/Ödül ve Takditler 2 Tarih : </strong> {#kursseminer2_tarih#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Kurs/Seminer/Sertifika/Ödül ve Takditler 3 Konu : </strong> {#kursseminer3_konu#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Kurs/Seminer/Sertifika/Ödül ve Takditler 3 Kurum : </strong> {#kursseminer3_kurum#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Kurs/Seminer/Sertifika/Ödül ve Takditler 3 Süre : </strong> {#kursseminer3_sure#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Kurs/Seminer/Sertifika/Ödül ve Takditler 3 Tarih : </strong> {#kursseminer3_tarih#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Üye Olduğunuz Dernek ve Kuruluşlar : </strong> {#uyeoldugunuzdernekkurulus#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Hobileriniz : </strong> {#hobileriniz#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Herhangi bir sağlık probleminiz var mı? : </strong> {#saglikproblemi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Mahkumiyet durumunuz var mı? : </strong> {#mahkumiyet#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Referans 1 Ad Soyad : </strong> {#referans1_adsoyad#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Referans 1 Çalıştığı Kurum : </strong> {#referans1_calistigikurum#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Referans 1 Görevi : </strong> {#referans1_gorevi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Referans 1 Telefon : </strong> {#referans1_telefonnumarasi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Referans 2 Ad Soyad : </strong> {#referans2_adsoyad#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Referans 2 Çalıştığı Kurum : </strong> {#referans2_calistigikurum#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Referans 2 Görevi : </strong> {#referans2_gorevi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Referans 2 Telefon : </strong> {#referans2_telefonnumarasi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Referans 3 Ad Soyad : </strong> {#referans3_adsoyad#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Referans 3 Çalıştığı Kurum : </strong> {#referans3_calistigikurum#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Referans 3 Görevi : </strong> {#referans3_gorevi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Referans 3 Telefon : </strong> {#referans3_telefonnumarasi#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <strong>Ücret Beklentiniz : </strong> {#ucretbeklentiniz#} <br style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
                 <p style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 5px 0;">&nbsp;</p>
             </td>
         </tr>
         <tr style="font-family: Calibri,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
          
      </tr>
  </table>